---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: redpencil/tika
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: redpencil/tika
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: redpencil/tika
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: DK6xj+C3wEsKODzb3l97tIcFdmDtdIauusyHUeID8OcltyzMh0U6
---
kind: secret
name: docker_password
data: 6WqRTJru2BIzHJmbxDqdt2cia8HrxNsk6kHmOGCZsrabICYqy3Z4Q0MJfWPu3PP0ooQAS0vWzZSQl0ZW1jk/lA==
---
kind: signature
hmac: 8eabe3db88e7be3ba64d4ededb2901ce0b83955754b5e9fe285fc4c3f382caa8

...
